#!/bin/bash
if [ ! -d "~/sikchat/build" ]
then
	mkdir ~/sikchat/build
	mkdir ~/sikchat/build/public
	mkdir ~/sikchat/build/public/js
	mkdir ~/sikchat/build/public/css
fi

cp ~/sikchat/*.js ~/sikchat/build/ 
cp ~/sikchat/*.json ~/sikchat/build/ 
cp ~/sikchat/index.html ~/sikchat/build/ 
terser ~/sikchat/public/js/general_ui.js -o ~/sikchat/build/public/js/general_ui.js -c -m
sass ~/sikchat/public/css/sikchat.scss ~/sikchat/build/public/css/sikchat.css